### ISSUE TITLE
Display none

### ISSUE THREAD

**Issue by michaeltrilford** [FreddyFY/styled-container-query#7]
I'm trying to get the following to work, but it seems there is a bug. When "display: none;" is introduced, the entire query doesn't work. If I switch out 'none' for block, it will work as intended. Unsure if this has been discovered before?

```
const Header = styledContainerQuery.div`
  display: none;
  &:container(min-width: 768px) {
    background: blue;
    display: flex;
  }
`;
```

**Comment by FreddyFY** [comment]
Hi @michaeltrilford

Yes this is a known issue. The problem here, is that once a container has `display: none`, it doesn't have a width or height eighter. So it styled-container-query can't calculate with it anymore.
The same happes when you try to change the width inside a container-query.

To solve this, you have two options:
1. With `opacity: 0`, or `visibility: hidden`
or
2. Style the child-element [better solution]
Create a second container inside the Header component, and style this one.
```javascript
const HeaderWrapper = styled.div`
  display: none:
`

const Header = styledContainerQuery.div`
  &:container(min-width: 768px) {
    background: blue;

    ${HeaderWrapper} {
      display: flex;
    }
  }
`;

({children}) => (
<Header>
  <HeaderWrapper>
    {children}
  </HeaderWrapper>
</Header>
)
```

Hope this helpes

**Comment by michaeltrilford** [comment]
That sounds like a good work around to the problem, thanks for the help ;-)
